name: CI

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test command
        run: exit 1 
  test:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: echo "This is the test job"    