name: CI

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

  workflow_dispatch:

env:
  APP_ENV: dev

jobs:
  hello:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run test command
        run: echo "GitHub Actions is working"
      - name: Show workflow variable
        run: echo "Environment is $APP_ENV"
      - name: Show repository
        run: echo "Repository is $GITHUB_REPOSITORY"    
      - name: Show commit SHA
        run: echo "Commit is $GITHUB_SHA"         
      - name: Show Git ref
        run: echo "Git ref is $GITHUB_REF" 
      - name: Use secret
        env:
          DEMO_TOKEN: ${{ secrets.DEMO_TOKEN }}
        run:  |
          if [ -n "$DEMO_TOKEN" ]; then
            echo "Secret is available"
          else
            echo "Secret is missing"
            exit 1
          fi 
      - name: Show repository variable
        env:
          DEPLOY_ENV: ${{ vars.DEPLOY_ENV }}
        run: echo "Deploy environment is $DEPLOY_ENV"
      - name: Show environment variable
        env:
          APP_URL: ${{ vars.APP_URL }}
        run: echo "App URL is $APP_URL" 
      - name: Check environment secret
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          if [ -n "$DEV_TOKEN" ]; then
            echo "Environment secret is available"
          else
            echo "Environment secret is missing"
            exit 1
          fi 
  test:
    needs: hello
    if: ${{ github.ref == 'refs/heads/main' }}   
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: echo "This is the test job"    